spring:
  application:
    name: "sock-service"

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/socks"

  jpa:
    hibernate:
      ddl-auto: create-drop
